sonar.projectKey=andminin-engineering_payment-orchestration-platform
sonar.organization=andminin-biz
sonar.projectName=payment-orchestration-platform

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=**/config/**,**/*Application.java,**/api/**/dto/**
